name: selfhosted

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Software
      run: |
        sudo apt-get install -y libtbb-dev clang-${{matrix.version}}
        sudo apt-get install -y libomp-${{matrix.version}}-dev libomp5-${{matrix.version}}

    - name: build sat solvers
      shell: bash
      run: |
        ./build.sh

    - name: run sat solvers
      shell: bash
      run: |
        ./run.sh
    
    - name: Pack
      working-directory: ${{github.workspace}}/results
      run: |
        tar -czf sCI_${{matrix.os}}_${{matrix.compiler}}.tar.gz CI

    - name: save results
      uses: actions/upload-artifact@v4
      with:
        name: sCI_${{matrix.os}}_${{matrix.compiler}}
        path: ${{github.workspace}}/results/sCI_${{matrix.os}}_${{matrix.compiler}}.tar.gz
